config/routes.rb
Rails.application.routes.draw do
	root "home#index"
  
  get 'messages/show' => 'messages#show'

#  get '/friendships' => 'friendships#show'
 # post '/friendships' => 'friendships#create'
  #delete '/friendships' => 'friendships#destroy'

#  post 'add_friend' => 'friendships#create'
#  delete 'delete_friend' => 'friendships#destroy'
	
	resources :friendships
	
	resources :sessions, only: [:new, :create]

	resources :users do
		resources :messages do
			collection do
				get :sent
				get :received
			end
			member do
				get 'mark_as_unread'
			end
		end
	end

=begin
	resources :messages do
	  member do
	    get 'mark_as_unread'
	  end
	end
=end

	delete 'logout' => 'sessions#destroy'



	get '/profile' => 'users#edit'

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user, :class_name => "User"
  belongs_to :friend, :class_name => "User"
#  has_many :friends   I think the user has_many :friends, through: :friendships takes care of this
end

app/models/message.rb
class Message < ApplicationRecord
	belongs_to :sender, class_name: 'User', foreign_key: :sender_id
	belongs_to :recipient, class_name: 'User', foreign_key: :recipient_id

	scope :unread, -> {where(read_at: nil)}

=begin
			Don't know if below is supposed to be there
=end
	def sent_messages
		Message.where(sender: self)
	end


	def mark_as_read!
		self.read_at ||= Time.now
		save!
	end

	def read?
		read_at
	end

end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password

	has_many :friendships, dependent: :destroy #user has many friendships which can be deleted/destroyed
	has_many :friends, :through => :friendships #cannot delete the friend, but can delete the friendship
	
	has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
	has_many :inverse_friends, :through => :inverse_friendships, :source => :user

	has_many :messages

#	def authenticate(some_password)
#		sth = encrypt some_password
#		compare password_digest == sth
#	end
	validates :email, presence: true, uniqueness: { case_insensitive: true }
	validates :name, presence: true

	def sent_messages
		Message.where(sender: self) #because you want the sent messages for the current user
	end

	def received_messages
		Message.where(recipient: self)
	end

	def latest_received_messages(n)
		received_messages.order(created_at: :desc).limit(n)
	end

	def unread_messages
		received_messages.unread
	end
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

 # before_action :authenticate

  helper_method :current_user, :user_signed_in?

  def current_user
  	return @current_user if @current_user

  	if session[:user_id]
  		User.find_by_id session[:user_id]
  	end
  end


 # def authenticate
 #   redirect_to new_session_path unless
#  end


  def user_signed_in?
    current_user != nil
  end

end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
#  before_action :authenticate

#  @friendships = Friendship.all
#  @users = User.inverse_friends(:current_user)
  def index
    @user = current_user
    @friendships = Friendship.all
  end

  def create
  	@friendship = current_user.friendships.build(:friend_id => params[:friend_id])
  	if @friendship.save
  		flash[:notice] = "Added friend."
  		redirect_to users_path
  	else
  		flash[:error] = "Unable to add friend."
  		render 'new'
  	end
  end

  def destroy
#    @friend = User.find(params[:user_id])
  	@friendship = current_user.friendships.find(params[:id]) #this supposed to find the friendship by the parameters friend_id. 
  	@friendship.delete
  	flash[:notice] = "Successfully removed (now former) friend."
  	redirect_to friendships_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
  #@messages = User.where(:user_id => current_user.id).order("created_at DESC") #trying to if current_user is user logged in, then view only messages in which current_user is recipient. 
  @messages = Message.all.order('created_at desc')
  end

  def new
    @message = Message.new
    @user = current_user
    @recipients = User.all
    @users = User.all
  end

  def create
  	@user = User.find(params[:user_id])
   # @message = Message.new
  #  @message.sender_id = current_user.id
  	@message = @user.sent_messages.build message_params

  	if @message.save
      flash[:success] = "Message Sent!"
      redirect_to received_user_messages_path
  	else
  		flash[:alert] = "Great Scott!"
      render 'new'
  	end
  end

  def show
  	@message = Message.find(params[:id])
  	if !@message.read? && current_user == @message.recipient
  		@message.mark_as_read!
  	end
  end

  def sent
  	load_user
  	@messages = @user.sent_messages.order("created_at DESC")
  end

  def received
  	load_user
  	@messages = @user.received_messages.order("created_at DESC")
  end

  def load_user
  	if params[:user_id]
  		@user = User.find params[:user_id]
  	else
  		@user = current_user
  	end
  end

  def mark_as_read!
    self.read_at = Time.now
    save!
  end

  def read?
    read_at
  end


  private
  
  def message_params
  	params.require(:message).permit(:recipient_id, :title, :body)
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
 # skip_before_action :authenticate, only: [:new, :create]

  def new
    redirect_to user_path(:id) if user_signed_in? and return
  end

  def destroy
  	session[:user_id] = nil
  	flash[:success] = "Logged out."

  	redirect_to root_path
  end

  def create
  	if @user = User.find_by(email: params[:email]) and @user.authenticate(params[:password])
  			session[:user_id] = @user.id
  			redirect_to received_user_messages_path(@user.id), flash: {success: "Logged In"}
  		else
  			flash.now[:error] = "Invalid username or password."
  			render 'new'
  		end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@users = User.all
	end

	def new
		@user = User.new
	end

	def show
		@user = current_user
	end

	def create
		@user = User.create user_params
		if @user.persisted? #save
			session[:user_id] = @user.id 
			flash[:success] = "Registered successfully"
			redirect_to new_session_path
		else
			flash.now[:error] = "Error: #{@user.errors.full_messages.to_sentence}"
			render'new' #means will render new html.erb file
		end
	end

	private

	def user_params
		params.require(:user).permit(:name, :email, :password, :password_confirmation)

	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
	def unread
		
	end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
	def flash_class_name(key)
		case key.to_s
		when 'success'
			"alert-success"
		when 'error'
			"alert-danger"
		else
			"alert-warning"
		end
	end
end

app/views/friendships/create.html.erb
<h1>Friendships#create</h1>
<p>Find me in app/views/friendships/create.html.erb</p>

app/views/friendships/index.html.erb
<div class="nav nav-inline">

<%= link_to 'Find friends', users_path, class: "nav-item btn btn-secondary" %>
<%= link_to 'Back to messages', received_user_messages_path(current_user), class: "nav-item btn btn-secondary" %>

</div>

<div class="col-lg-12">



<div class="col-sm-8">
  <h3>Following</h3>
  <table class="table col-sm-8">
    <thead class="thead-inverse">
      <tr>
        <th>Friend Id</th>
        <th>Name</th>
        <th>Email</th>

        <th> </th>
      </tr>
    </thead>
    <tbody>
    <% for friendship in @user.friendships %>
      <tr>
        <td><%=h friendship.friend.id %></td>
        <td><%=h friendship.friend.name %></td>
        <td><%=h friendship.friend.email %></td>
        <td>(<%= link_to "Unfollow", friendship, :method => :delete, data: { confirm: 'Are you sure?' }  %>)</td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>



<div class="col-sm-4">
  <h3>Followers</h3>
  <table class="table col-sm-4">
    <thead class="thead-inverse">
      <tr>
        <th>Name</th>
        <th>Email</th>
      </tr>
    </thead>
    <tbody>
    <% for user in @user.inverse_friends %>
    <tr>
      <td><%=h user.name %></td>
      <td><%=h user.email %></td>
    </tr>
    <% end %>
    </tbody>
  </table>
</div>

</div>



<%#
<%= link_to 'View friends', friendship_path(:user_id), class: "nav-item btn btn-primary" %>

app/views/friendships/show.html.erb
<h3>Friends List</h3>

app/views/home/index.html.erb
<h1>ChatApp</h1>

<nav class="nav nav-inline">
<%= link_to "Sign Up", new_user_path, class: "nav-link" %>

<%= link_to "Login", new_session_path, class: "nav-link" %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChatApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
    	<% if current_user %>
      	<div class="alert alert-info">
      		Welcome, <%= current_user.name %>. Not you?
          <%= link_to "Log out", logout_path, method: 'delete' %> |
          <%= link_to "Home", received_user_messages_path(current_user) %>
      	</div>
      <% else %>
        <% link_to "Log in", new_session_path %>
      <% end %>

    	<% if flash.any? %>
    		<% flash.each do |key, value| %>
    			<div class="alert <%= flash_class_name(key) %>">
    				<%= value %>
    			</div>
    		<% end %>

    	<% end %>

        <nav class="navbar navbar-light bg-faded">
          <%= link_to "ChatApp", root_path, class: 'navbar-brand' %>
          <ul class="nav navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="">Contact</a>
            </li>
          </ul>




          <form class="form-inline pull-xs-right" action="/menu" method="GET">
               <%= text_field_tag :search, params[:search], class: "form-control",placeholder: "Search" %>
               <button class="btn btn-success-outline" type="submit">Search</button>
          </form>
        </nav>


<%#      <% if flash[:error] %>
<%#        <div class="alert alert-danger"><%= flash[:error] %><!--</div>
<%#      <% end %>
<%#      <% if flash[:success] %>
<%#        <div class="alert alert-success"><%= flash[:success] %></div>
<%#       <% end %> -->

       
      <%= yield %>

    </div>
  </body>
</html>

app/views/messages/_form.html.erb
<div class="card col-sm-6">
	<div class="card-block">
		<div class="row">

			<%= form_for [@user, @message] do |f| %>
				<div class="form-control">
				  <%= f.label :recipient_id %>
				  <%= f.select :recipient_id, @users.map {|u| [u.email, u.id]} %>
				</div>
				 <div class="form-control">
				  <%= f.label :title %>
				  <%= f.text_field :title %>
				</div>

				<div class="form-control input-lg">
				  <%= f.label :body %>
				  <%= f.text_field :body %>
				</div>

				  <%= f.submit "Send Message", class: 'btn btn-primary' %>
			<% end %>
		</div>
	</div>
</div>

app/views/messages/_message.html.erb
<div class="row">
  <div class="col-sm-8">
      <div class="card">

        <div class="card-block">
          <h4 class="card-title">

    <!-- if recipient id == current_user, then it's link_to messages#show --> 
      <% if message.recipient_id == current_user.id && message.read_at == nil %>
          <%= link_to message.title, user_message_path(id: message.id) %>
          <% else %>
          <%= message.title %>
          <% end %> 
<!-- ^^ supposed to go to messages/id where id = message_id-->
          </h4>
          <p class="card-text">
            <% if message.read_at == nil %>
            <strong><%= message.body %> </strong>
          </p>
            <% else %>
            <%= message.body %>
             <% end %>
        </div>
           

        <div class="card-footer">
          <% if message.recipient_id == current_user.id %> 
            From: <%= message.sender.name %> 
          <% else %>
            To: <%= message.recipient.name %>
          <% end %>


          Read at: <% if message.read_at == nil %>
          <strong> unread </strong>
          <% else %>
          <%= message.read_at %>
          <% end %>

        </div>
      </div>
  </div>
</div>

app/views/messages/index.html.erb
<ul class="nav nav-pills">
  <li class="nav-item">
  	<%= link_to "New Message", new_user_message_path, class: "nav-link" %>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="#">Sent Messages</a>
  </li>
  <li class="nav-item">
  	<%= link_to "Find friends", users_path, class: "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to "View friends", friendships_path, class: "nav-link" %>
  </li>
</ul>

<%= render @messages %>

<% if message.read_at == nil %>
<strong><%= message.last.content> </strong>
<% end %>

app/views/messages/new.html.erb
<h3>Send New Message <h4>

<ul class="nav nav-pills nav-stacked col-sm-4" >
  <li class="nav-item">
    <%= link_to "Back to Messages", received_user_messages_path, class: "nav-link btn btn-secondary" %>
  </li>  
  <li class="nav-item">
    <%= link_to "Sent Messages", sent_user_messages_path, class: "nav-link btn btn-secondary	" %>
  </li>
</ul>

<%= render 'form', message: @message %>

app/views/messages/received.html.erb
<ul class="nav nav-pills nav-stacked col-sm-4" >
  <li class="nav-item">
    <%= link_to "Received Messages", received_user_messages_path, class: "nav-link active" %>
  </li>  
  <li class="nav-item">
    <%= link_to "Sent Messages", sent_user_messages_path, class: "nav-link" %>
  </li>
</ul>

<ul class="nav nav-pills">
  <li class="nav-item">
  	<%= link_to "New Message", new_user_message_path, class: "nav-link" %>
  </li>
  <li class="nav-item">
  	<%= link_to "Find friends", users_path, class: "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to "View friends", friendships_path, class: "nav-link" %>
  </li>
</ul>
<!--
<ul class="nav nav-pills">
<%#  <% Messages.all.each do |message| %>
    <li class="nav-item">
 
<%#      <%= link_to cuisine.name, menu_path(cuisine: cuisine.name), class: "nav-link #{'active' if params[:cuisine] == cuisine.name}" %>

    </li>
<%#  <% end %>
</ul>
-->

<%= render @messages %> 


<%#class: "#{strong if @message.read_at == nil}" %>

app/views/messages/sent.html.erb
<ul class="nav nav-pills nav-stacked col-sm-4" >
  <li class="nav-item">
    <%= link_to "Received Messages", received_user_messages_path, class: "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to "Sent Messages", sent_user_messages_path, class: "nav-link active" %>
  </li>

</ul>

<ul class="nav nav-pills">
  <li class="nav-item">
  	<%= link_to "New Message", new_user_message_path, class: "nav-link" %>
  </li>

  <li class="nav-item">
  	<%= link_to "Find friends", users_path, class: "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to "View friends", friendships_path, class: "nav-link" %>
  </li>
</ul>


<%= render @messages %> <%#, class: "#{strong if !!@message.read?}" %>

app/views/messages/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @message.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @message.body %>
</p>

<p>
	<strong>Sender:</strong>
	<%= @message.sender.name %>

	<strong>Recipient:</strong> <%= @message.recipient.name %>
	</p>



<%= link_to 'Back to Messages', received_user_messages_path, class: "btn btn-secondary" %>

app/views/users/index.html.erb
	<h1>Users</h1>


	<table class="table">
		<thead class="thead thead-default">
			<tr>
				<th>Full Name</th>
				<th>Email</th>
				<th>Created at</th>
				<th>Action</th>
			</tr>
		</thead>
		<tbody>
			<% @users.each do |user| %>
			<tr>
				<td><%= user.name %></td>
				<td><%= user.email %></td>
				<td><%= user.created_at.to_formatted_s(:long_ordinal) %></td>
				<td><%= link_to "Add Friend", friendships_path(:friend_id => user), method: :post  %></td>
			</tr>
			<% end %>
		</tbody>
	</table>

app/views/users/new.html.erb
<h1>Create An Account</h1>

<%= form_for @user do |f| %>
<div class="form-group">
	<%= f.label :name %>
	<%= f.text_field :name, placeholder: "Enter your full name.", class: 'form-control' %>
</div>

<div class="form-group">
	<%= f.label :email %>
	<%= f.text_field :email, placeholder: "Enter your email...", class: 'form-control' %>
</div>

<div class="form-group">
	<%= f.label :password %>
	<%= f.password_field :password, class: 'form-control' %>
</div>
	<%= f.submit "Create Account", class: 'btn btn-secondary' %>
	<% end %>

<form action="/users" method="post">

</form>

app/views/users/show.html.erb
<div class="container">
<div class="col-sm-3">
<h1><%= "Welcome #{current_user.name}!" %></h1>

<%= link_to 'Messages', user_messages_path(:id), class: "nav-item btn btn-primary" %>
</div>

  <div class="col-sm-6">
    <strong>Name:</strong>
    <%= @user.name %>

    <p>
    <strong>Email:</strong>
    <%= @user.email %>
    </p>
  </div>

<div class="col-sm-6">
<h3>Friends</h3>

<table class="table col-sm-4">
  <thead class="thead-inverse">
    <tr>
      <th>Friendship ID</th>
      <th>Friend Id</th>
      <th>Name</th>
      <th>Email</th>

      <th> </th>
    </tr>
  </thead>
  <tbody>
  <% for friendship in @user.friendships %>
  <tr>
    <td><%=h friendship.id %></td>
    <td><%=h friendship.friend.id %></td>
    <td><%=h friendship.friend.name %></td>
    <td><%=h friendship.friend.email %></td>
    <td>(<%= link_to "remove", friendship_path(friendship), :method => :delete, data: { confirm: 'Are you sure?' }  %>)</td>
  </tr>
  <% end %>
  </tbody>
</table>
<%= link_to 'Find friends', users_path, class: "nav-item btn btn-primary" %>

<%= link_to 'View friends', friendships_path, class: "nav-item btn btn-primary" %>
</div>



<div class="col-sm-4">
<h3>Friended by Users</h3>

<table class="table col-sm-4">
  <thead class="thead-inverse">
    <tr>
      <th>Name</th>
      <th>Email</th>
    </tr>
  </thead>
  <tbody>
  <% for user in @user.inverse_friends %>
  <tr>
    <td><%=h user.name %></td>
    <td><%=h user.email %></td>
  </tr>
  <% end %>
  </tbody>
</table>




</div>